# Generated by Django 4.0.6 on 2022-07-06 12:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=256, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Номер телефона клиента')),
                ('name', models.CharField(max_length=256, verbose_name='Имя клиента')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2022, 7, 6, 12, 8, 37, 521422, tzinfo=utc), verbose_name='Дата бронирования')),
                ('time_start', models.TimeField(verbose_name='Время начала приёма')),
                ('time_end', models.TimeField(verbose_name='Время конца приёма')),
                ('is_visited', models.BooleanField(default=False, verbose_name='Посещен ли приём')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client', verbose_name='Клиент')),
            ],
        ),
    ]
