# Generated by Django 4.0.6 on 2022-07-07 19:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_client_options_alter_client_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 7, 19, 56, 35, 796858, tzinfo=utc), verbose_name='Дата бронирования'),
        ),
    ]
