# Generated by Django 4.0.6 on 2022-07-07 19:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 7, 19, 56, 43, 709402, tzinfo=utc), verbose_name='Дата бронирования'),
        ),
    ]
