# Generated by Django 4.0.6 on 2022-07-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_client_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='duration',
            field=models.IntegerField(default=60, verbose_name='Длительность приёма(мин)'),
        ),
    ]
